### 생성
POST http://158.247.197.4:8084/example
Content-Type: application/json

{
  "content": "AsdasdasdasdasdasdfaasDaSdsadfsfesaef"
}

### 조회
GET {{url}}/example?exampleInfoNo=3
Content-Type: application/json
Member-Code: eyJubyI6MSwibmFtZSI6Im5hbWUiLCJhY2NvdW50IjoiYWNjb3VudCJ9


### 일정 등록
POST {{url}}/schedule
Content-Type: application/json
Member-Code: eyJubyI6NywibmFtZSI6Im5hbWUiLCJhY2NvdW50IjoiYWNjb3VudCJ9

{
  "busyLevel": "여유",
  "scheduleName": "일정 1",
  "scheduleLocation": "서울",
  "scheduleWith": "예지 공통 스케줄",
  "groupGenderType": "여",
  "scheduleStartAt": "2024-01-11T20:00:00",
  "scheduleEndAt": "2024-01-11T23:00:00",
  "scheduleAt": "2024-09-03",
  "isCommon": true
}

### 특정 날짜 일정 조회
GET https://togethery.store/api/schedule?searchDate=2024-09-26
Content-Type: application/json
Member-Code: eyJubyI6MiwibmFtZSI6Im5hbWUiLCJhY2NvdW50IjoiYWNjb3VudCJ9


### 일정 상세 조회
GET {{url}}/schedule/detail/1
Content-Type: application/json
Member-Code: eyJubyI6MSwibmFtZSI6Im5hbWUiLCJhY2NvdW50IjoiYWNjb3VudCJ9

### (커플) 특정 날짜 일정 조회
GET {{url}}/schedule/couple?searchDate=2024-09-26
Content-Type: application/json
Member-Code: eyJubyI6MSwibmFtZSI6Im5hbWUiLCJhY2NvdW50IjoiYWNjb3VudCJ9

### 일정 삭제
DELETE {{url}}/schedule/7
Content-Type: application/json

### 일정 삭제
PUT {{url}}/schedule/7/status?status=종료
Content-Type: application/json

### 공통 일정
GET {{url}}/schedule/common?searchDate=2024-09-26
Content-Type: application/json
Member-Code: eyJubyI6MSwibmFtZSI6Im5hbWUiLCJhY2NvdW50IjoiYWNjb3VudCJ9


### FCM 알림 전송
POST https://fcm.googleapis.com/v1/projects/togethery-52df6/messages:send
Authorization: Bearer {{ACCESS_TOKEN}}
Content-Type: application/json

{
  "message": {
    "token": "YOUR_DEVICE_FCM_TOKEN",
    "notification": {
      "title": "Hello from IntelliJ",
      "body": "This is a test notification sent via IntelliJ!"
    },
    "data": {
      "key1": "value1",
      "key2": "value2"
    }
  }
}


### 알림
POST http://localhost:8084/example/noti
Content-Type: application/json


### invite-code
POST {{url}}/account-service/couple/invite-code
Member-Code:eyJubyI6NSwibmFtZSI6Im5hbWUiLCJhY2NvdW50IjoiYWNjb3VudCJ9


### test-noti
POST {{url}}/notification/test
Content-Type: application/json

{
  "memberNo": 15,
  "title": "테스트",
  "body": "body",
  "uri": "/"
}